spring:
  application:
    name: shopping-service
  profiles:
    active: dev
  cloud:
    openfeign:
      circuitbreaker:
        enabled: true
        alphanumeric-ids:
          enabled: true
      client:
        config:
          default:
            connectTimeout: 5000
            readTimeout: 5000
            loggerLevel: basic
server:
  servlet:
    context-path: /store/api/v1
  port: 9070
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9010/eureka
feign:
  #  circuitbreaker:
  #    enabled: true
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
